// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get basic service information",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Service information",
                "responses": {
                    "200": {
                        "description": "Service information",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check service health status including MongoDB and Redis connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get Prometheus metrics for monitoring (requires API key)",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Check service readiness for traffic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        },
        "/twirp/chat.ChatService/ContinueConversation": {
            "post": {
                "description": "Continue an existing conversation with the AI assistant. Supports both direct conversation_id and session-based conversations for stateless clients.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Continue an existing conversation",
                "parameters": [
                    {
                        "description": "Continue conversation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ContinueConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ContinueConversationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/twirp/chat.ChatService/DescribeConversation": {
            "post": {
                "description": "Get detailed information about a specific conversation including all messages.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Get conversation details",
                "parameters": [
                    {
                        "description": "Describe conversation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DescribeConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DescribeConversationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/twirp/chat.ChatService/ListConversations": {
            "post": {
                "description": "Get list of recent conversations. Messages are excluded from the response to avoid large payloads.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "List conversations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ListConversationsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/twirp/chat.ChatService/StartConversation": {
            "post": {
                "description": "Create a new conversation with the AI assistant. The assistant can answer questions, provide weather information, date/time, and holiday information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Start a new conversation",
                "parameters": [
                    {
                        "description": "Start conversation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.StartConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.StartConversationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ContinueConversationRequest": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "message": {
                    "type": "string",
                    "example": "What about tomorrow?"
                },
                "session_metadata": {
                    "$ref": "#/definitions/main.SessionMetadata"
                }
            }
        },
        "main.ContinueConversationResponse": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string",
                    "example": "Tomorrow will be partly cloudy with 20°C..."
                }
            }
        },
        "main.Conversation": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Message"
                    }
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-11-07T20:15:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Weather discussion"
                }
            }
        },
        "main.DescribeConversationRequest": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                }
            }
        },
        "main.DescribeConversationResponse": {
            "type": "object",
            "properties": {
                "conversation": {
                    "$ref": "#/definitions/main.Conversation"
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "details": {
                    "type": "string",
                    "example": "Missing required field: message"
                },
                "message": {
                    "type": "string",
                    "example": "Bad Request"
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "mongodb": "ok",
                        "redis": "ok"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "main.ListConversationsResponse": {
            "type": "object",
            "properties": {
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Conversation"
                    }
                }
            }
        },
        "main.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "What's the weather like?"
                },
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439012"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-11-07T20:15:00Z"
                }
            }
        },
        "main.SessionMetadata": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "string",
                    "example": "67890"
                },
                "platform": {
                    "type": "string",
                    "example": "telegram"
                },
                "user_id": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "main.StartConversationRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "What's the weather in Barcelona?"
                },
                "session_metadata": {
                    "$ref": "#/definitions/main.SessionMetadata"
                }
            }
        },
        "main.StartConversationResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "reply": {
                    "type": "string",
                    "example": "The weather in Barcelona is sunny with 22°C..."
                },
                "title": {
                    "type": "string",
                    "example": "Weather in Barcelona"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
