// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc/chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversation_Role int32

const (
	Conversation_UNKNOWN   Conversation_Role = 0
	Conversation_USER      Conversation_Role = 1
	Conversation_ASSISTANT Conversation_Role = 2
)

// Enum value maps for Conversation_Role.
var (
	Conversation_Role_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER",
		2: "ASSISTANT",
	}
	Conversation_Role_value = map[string]int32{
		"UNKNOWN":   0,
		"USER":      1,
		"ASSISTANT": 2,
	}
)

func (x Conversation_Role) Enum() *Conversation_Role {
	p := new(Conversation_Role)
	*p = x
	return p
}

func (x Conversation_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Conversation_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_chat_proto_enumTypes[0].Descriptor()
}

func (Conversation_Role) Type() protoreflect.EnumType {
	return &file_rpc_chat_proto_enumTypes[0]
}

func (x Conversation_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Conversation_Role.Descriptor instead.
func (Conversation_Role) EnumDescriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{0, 0}
}

type Conversation struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Messages      []*Conversation_Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_rpc_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Conversation) GetMessages() []*Conversation_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type StartConversationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionMetadata *SessionMetadata       `protobuf:"bytes,2,opt,name=session_metadata,json=sessionMetadata,proto3" json:"session_metadata,omitempty"` // NEW optional field
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartConversationRequest) Reset() {
	*x = StartConversationRequest{}
	mi := &file_rpc_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConversationRequest) ProtoMessage() {}

func (x *StartConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConversationRequest.ProtoReflect.Descriptor instead.
func (*StartConversationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{1}
}

func (x *StartConversationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartConversationRequest) GetSessionMetadata() *SessionMetadata {
	if x != nil {
		return x.SessionMetadata
	}
	return nil
}

type StartConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Reply          string                 `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartConversationResponse) Reset() {
	*x = StartConversationResponse{}
	mi := &file_rpc_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConversationResponse) ProtoMessage() {}

func (x *StartConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConversationResponse.ProtoReflect.Descriptor instead.
func (*StartConversationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{2}
}

func (x *StartConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StartConversationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartConversationResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ContinueConversationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`    // EXISTING field
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                        // EXISTING field
	SessionMetadata *SessionMetadata       `protobuf:"bytes,3,opt,name=session_metadata,json=sessionMetadata,proto3" json:"session_metadata,omitempty"` // NEW optional field
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContinueConversationRequest) Reset() {
	*x = ContinueConversationRequest{}
	mi := &file_rpc_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueConversationRequest) ProtoMessage() {}

func (x *ContinueConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueConversationRequest.ProtoReflect.Descriptor instead.
func (*ContinueConversationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ContinueConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ContinueConversationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContinueConversationRequest) GetSessionMetadata() *SessionMetadata {
	if x != nil {
		return x.SessionMetadata
	}
	return nil
}

type SessionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // "telegram", "web", "api"
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMetadata) Reset() {
	*x = SessionMetadata{}
	mi := &file_rpc_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMetadata) ProtoMessage() {}

func (x *SessionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMetadata.ProtoReflect.Descriptor instead.
func (*SessionMetadata) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SessionMetadata) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SessionMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionMetadata) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ContinueConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueConversationResponse) Reset() {
	*x = ContinueConversationResponse{}
	mi := &file_rpc_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueConversationResponse) ProtoMessage() {}

func (x *ContinueConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueConversationResponse.ProtoReflect.Descriptor instead.
func (*ContinueConversationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ContinueConversationResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_rpc_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{6}
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_rpc_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type DescribeConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeConversationRequest) Reset() {
	*x = DescribeConversationRequest{}
	mi := &file_rpc_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeConversationRequest) ProtoMessage() {}

func (x *DescribeConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeConversationRequest.ProtoReflect.Descriptor instead.
func (*DescribeConversationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DescribeConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeConversationResponse) Reset() {
	*x = DescribeConversationResponse{}
	mi := &file_rpc_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeConversationResponse) ProtoMessage() {}

func (x *DescribeConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeConversationResponse.ProtoReflect.Descriptor instead.
func (*DescribeConversationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{9}
}

func (x *DescribeConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type Conversation_Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          Conversation_Role      `protobuf:"varint,2,opt,name=role,proto3,enum=acai.chat.Conversation_Role" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation_Message) Reset() {
	*x = Conversation_Message{}
	mi := &file_rpc_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation_Message) ProtoMessage() {}

func (x *Conversation_Message) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation_Message.ProtoReflect.Descriptor instead.
func (*Conversation_Message) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Conversation_Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation_Message) GetRole() Conversation_Role {
	if x != nil {
		return x.Role
	}
	return Conversation_UNKNOWN
}

func (x *Conversation_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Conversation_Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_rpc_chat_proto protoreflect.FileDescriptor

const file_rpc_chat_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/chat.proto\x12\tacai.chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12;\n" +
	"\bmessages\x18\x04 \x03(\v2\x1f.acai.chat.Conversation.MessageR\bmessages\x1a\x9f\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1c.acai.chat.Conversation.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\",\n" +
	"\x04Role\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tASSISTANT\x10\x02\"{\n" +
	"\x18StartConversationRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12E\n" +
	"\x10session_metadata\x18\x02 \x01(\v2\x1a.acai.chat.SessionMetadataR\x0fsessionMetadata\"p\n" +
	"\x19StartConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\"\xa7\x01\n" +
	"\x1bContinueConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12E\n" +
	"\x10session_metadata\x18\x03 \x01(\v2\x1a.acai.chat.SessionMetadataR\x0fsessionMetadata\"_\n" +
	"\x0fSessionMetadata\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\"4\n" +
	"\x1cContinueConversationResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"\x1a\n" +
	"\x18ListConversationsRequest\"Z\n" +
	"\x19ListConversationsResponse\x12=\n" +
	"\rconversations\x18\x01 \x03(\v2\x17.acai.chat.ConversationR\rconversations\"F\n" +
	"\x1bDescribeConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"[\n" +
	"\x1cDescribeConversationResponse\x12;\n" +
	"\fconversation\x18\x01 \x01(\v2\x17.acai.chat.ConversationR\fconversation2\x9f\x03\n" +
	"\vChatService\x12^\n" +
	"\x11StartConversation\x12#.acai.chat.StartConversationRequest\x1a$.acai.chat.StartConversationResponse\x12g\n" +
	"\x14ContinueConversation\x12&.acai.chat.ContinueConversationRequest\x1a'.acai.chat.ContinueConversationResponse\x12^\n" +
	"\x11ListConversations\x12#.acai.chat.ListConversationsRequest\x1a$.acai.chat.ListConversationsResponse\x12g\n" +
	"\x14DescribeConversation\x12&.acai.chat.DescribeConversationRequest\x1a'.acai.chat.DescribeConversationResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_rpc_chat_proto_rawDescOnce sync.Once
	file_rpc_chat_proto_rawDescData []byte
)

func file_rpc_chat_proto_rawDescGZIP() []byte {
	file_rpc_chat_proto_rawDescOnce.Do(func() {
		file_rpc_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_chat_proto_rawDesc), len(file_rpc_chat_proto_rawDesc)))
	})
	return file_rpc_chat_proto_rawDescData
}

var file_rpc_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_chat_proto_goTypes = []any{
	(Conversation_Role)(0),               // 0: acai.chat.Conversation.Role
	(*Conversation)(nil),                 // 1: acai.chat.Conversation
	(*StartConversationRequest)(nil),     // 2: acai.chat.StartConversationRequest
	(*StartConversationResponse)(nil),    // 3: acai.chat.StartConversationResponse
	(*ContinueConversationRequest)(nil),  // 4: acai.chat.ContinueConversationRequest
	(*SessionMetadata)(nil),              // 5: acai.chat.SessionMetadata
	(*ContinueConversationResponse)(nil), // 6: acai.chat.ContinueConversationResponse
	(*ListConversationsRequest)(nil),     // 7: acai.chat.ListConversationsRequest
	(*ListConversationsResponse)(nil),    // 8: acai.chat.ListConversationsResponse
	(*DescribeConversationRequest)(nil),  // 9: acai.chat.DescribeConversationRequest
	(*DescribeConversationResponse)(nil), // 10: acai.chat.DescribeConversationResponse
	(*Conversation_Message)(nil),         // 11: acai.chat.Conversation.Message
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_rpc_chat_proto_depIdxs = []int32{
	12, // 0: acai.chat.Conversation.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: acai.chat.Conversation.messages:type_name -> acai.chat.Conversation.Message
	5,  // 2: acai.chat.StartConversationRequest.session_metadata:type_name -> acai.chat.SessionMetadata
	5,  // 3: acai.chat.ContinueConversationRequest.session_metadata:type_name -> acai.chat.SessionMetadata
	1,  // 4: acai.chat.ListConversationsResponse.conversations:type_name -> acai.chat.Conversation
	1,  // 5: acai.chat.DescribeConversationResponse.conversation:type_name -> acai.chat.Conversation
	0,  // 6: acai.chat.Conversation.Message.role:type_name -> acai.chat.Conversation.Role
	12, // 7: acai.chat.Conversation.Message.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 8: acai.chat.ChatService.StartConversation:input_type -> acai.chat.StartConversationRequest
	4,  // 9: acai.chat.ChatService.ContinueConversation:input_type -> acai.chat.ContinueConversationRequest
	7,  // 10: acai.chat.ChatService.ListConversations:input_type -> acai.chat.ListConversationsRequest
	9,  // 11: acai.chat.ChatService.DescribeConversation:input_type -> acai.chat.DescribeConversationRequest
	3,  // 12: acai.chat.ChatService.StartConversation:output_type -> acai.chat.StartConversationResponse
	6,  // 13: acai.chat.ChatService.ContinueConversation:output_type -> acai.chat.ContinueConversationResponse
	8,  // 14: acai.chat.ChatService.ListConversations:output_type -> acai.chat.ListConversationsResponse
	10, // 15: acai.chat.ChatService.DescribeConversation:output_type -> acai.chat.DescribeConversationResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rpc_chat_proto_init() }
func file_rpc_chat_proto_init() {
	if File_rpc_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_chat_proto_rawDesc), len(file_rpc_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_chat_proto_goTypes,
		DependencyIndexes: file_rpc_chat_proto_depIdxs,
		EnumInfos:         file_rpc_chat_proto_enumTypes,
		MessageInfos:      file_rpc_chat_proto_msgTypes,
	}.Build()
	File_rpc_chat_proto = out.File
	file_rpc_chat_proto_goTypes = nil
	file_rpc_chat_proto_depIdxs = nil
}
